import type { Request, Response } from 'express';
import { DecryptService } from '../services/decrypt.service';
import { EncryptService } from '../services/encrypt.service';
import type { EncryptedPayload, EncryptRequest } from '../types/crypto.types';

/**
 * Handles HTTP requests for hybrid encryption and decryption.
 *
 * Controllers are intentionally thin: validation/orchestration happens here,
 * while cryptographic primitives remain isolated in services.
 */
export class CryptoController {
  /**
   * Encrypts a plaintext message received in the request body.
   *
   * @param {Request} req - Express request containing `{ message: string }`.
   * @param {Response} res - Express response.
   */
  static encrypt(req: Request, res: Response): void {
    const body = req.body as Partial<EncryptRequest> | undefined;

    if (typeof body?.message !== 'string' || body.message.length === 0) {
      res.status(400).json({
        message: 'The request must contain a non-empty string property named message.',
      });
      return;
    }

    try {
      const encrypted = EncryptService.encryptMessage(body.message);
      res.status(200).json(encrypted);
    } catch (error) {
      res.status(500).json({
        message: 'Encryption failed.',
        error: error instanceof Error ? error.message : 'Unknown error',
      });
    }
  }

  /**
   * Decrypts an encrypted payload generated by the encryption endpoint.
   *
   * @param {Request} req - Express request containing the encrypted payload.
   * @param {Response} res - Express response containing the original message.
   */
  static decrypt(req: Request, res: Response): void {
    const body = req.body as Partial<EncryptedPayload> | undefined;
    const requiredFields: Array<keyof EncryptedPayload> = [
      'encryptedKey',
      'iv',
      'authTag',
      'data',
    ];

    const hasAllFields = requiredFields.every(
      (field) => typeof body?.[field] === 'string' && body[field]!.length > 0,
    );

    if (!hasAllFields) {
      res.status(400).json({
        message: 'encryptedKey, iv, authTag and data are required as Base64 strings.',
      });
      return;
    }

    try {
      const message = DecryptService.decryptMessage(body as EncryptedPayload);
      res.status(200).json({ message });
    } catch (error) {
      res.status(400).json({
        message: 'Decryption failed. The payload may be corrupted or the key may be incorrect.',
        error: error instanceof Error ? error.message : 'Unknown error',
      });
    }
  }
}
